### PR TITLE
Introducing message transforming

### PR DESCRIPTION
**Pull request by synercoder**
Replaces idea brought up by #10

### CODE REVIEW

**Review by corstian — APPROVED** [review]

**Comment by corstian** [comment]
@ajbeaven, does this API set make sense to you?

**Review by corstian — APPROVED** [review]

**Comment by ajbeaven** [comment]
Love your work! All makes sense to me.

You'll have to clearly outline the use cases for both transform delegates and I would perhaps suggest not using terminology around, and making a distinction between, rendering and sending. Since both happen inside the one - now two - public methods, this seems to me like an internal implementation detail so I'm not sure how worthwhile it is burdening the consumer with this insight.

**Comment by synercoder** [comment]
@ajbeaven Good call, removed the mention of rendering in the XML comment

**Comment by corstian** [comment]
I've ran a few tests and everything seems to be working smoothly. The rc4 package has just been published over at https://www.nuget.org/packages/Skyhop.Mail/3.0.0-rc4, and will be available shortly. Thanks for the contributions!

**Pull request merged**
