### PR TITLE
Base model refactor

### PR DESCRIPTION
**Pull request by synercoder**
Only way to set the To, From, Cc & Bcc  are now using the MailDispatcher instead of also setting them in the MimeMessage. This makes the To parameter now required.

And the From parameter is optional, as long is the DefaultFromAddress is set. Otherwise an ArgumentException is thrown.

### CODE REVIEW

**Review by corstian — APPROVED** [review]
Thanks for these contributions :)

One thing I'm currently dabbling about in my mind (not related to this PR) is about whether the `attachments` parameter on the `SendMail` method is obsolete, by the `Attachments` property on the `MailBase`.

In the end both will end up in the same place. The `Attachments` property can be set from the view, which would be beneficial in some cases where static forms will need to be sent via email.

From my point of view, for consistency's sake, it would make sense to have only one place to add attachments, and I think it would be by adding them to the viewmodel.

**Comment by synercoder** [comment]
That was my (reversed) thinking why I removed the To & CC params from the ViewModel. To have just 1 place where you put them.

**Comment by corstian** [comment]
Would it be a reasonable separation to set the destination on the `SendMail` method, while setting the content within the viewmodel?

Trying to keep the cognitive load as low as possible...

**Comment by synercoder** [comment]
Sounds like a good plan

**Pull request merged**
